apiVersion: 1

datasources:
  - uid: influxdb
    name: influxdb
    type: influxdb
    isDefault: true
    editable: true
    access: proxy
    url: http://influxdb:8181

    jsonData:
      queryLanguage: sql
      database: ${INFLUXDB_BUCKET}
      dbName: ${INFLUXDB_BUCKET}
      organization: ${INFLUXDB_ORG}
      httpMode: POST
      insecureGrpc: true
      tlsSkipVerify: false
      secureSocksProxyEnabled: false
      version: SQL

    secureJsonData:
      token: ${INFLUXDB_TOKEN}

