[agent]
  interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  flush_interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  hostname = "${HOSTNAME}"

[[inputs.http]]
  urls = ["http://health-sensor-simulator:8000/api/v1/vitals"]
  data_format = "json"
  method = "GET"
  timeout = "5s"
  name_override = "health_vitals"

[[inputs.http_listener_v2]]
  service_address = ":8080"
  methods = ["POST"]
  data_format = "json"
  name_override = "alarms"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8181"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"